apiVersion: skaffold/v4beta7
kind: Config

manifests:
  helm:
    releases:
    - name: mock-eq
#      chartPath: oci://europe-west2-docker.pkg.dev/ras-rm-sandbox/charts/mock-eq
      chartPath: _infra/helm/mock-eq
      version: 2.0.2
      namespace: clouddeploy