apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
  - image: mock-eq
    context: .
    docker:
      dockerfile: _infra/docker/Dockerfile

manifests:
  helm:
    releases:
    - name: mock-eq
      chartPath: _infra/helm/mock-
#  rawYaml:
#    - k8s.yaml
deploy:
  kubectl: {}