apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
  - image: mock-eq
    context: .
    docker:
      dockerfile: _infra/docker/Dockerfile

manifests:
  helm:
    releases:
    - name: mock-eq
      chartPath: oci://europe-west2-docker.pkg.dev/ras-rm-cloud-deploy-sandbox/charts

deploy:
  kubectl: {}