apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: gga1812/mock-eq:1.2
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
      imagePullSecrets:
      - name: regcred
      # readinessProbe:
      #   httpGet:
      #       path: /info
      #       port: 8080
      #     initialDelaySeconds: 1
      #     periodSeconds: 20
      #     failureThreshold: 5
      #     successThreshold: 1
      #     timeoutSeconds: 5
      # livenessProbe:
      #     path: /info
      #     port: 8080
      #   initialDelaySeconds: 1
      #   periodSeconds: 20
      #   failureThreshold: 5
      #   successThreshold: 1
      #   timeoutSeconds: 5
