apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: kubernetes-services
      imagePullSecrets:
        - name: gar-secret
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: {{ .Chart.Name }}
        {{- if eq .Values.image.tag "latest"}}
        image: "{{ .Values.image.name}}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        {{- else}}
        image: "{{ .Values.image.devRepo }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
        {{- end}}
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: {{ .Values.container.port }}
        resources:
          {{ toYaml .Values.resources | nindent 12 }}
        env:
        - name: JSON_SECRET_KEYS
          valueFrom:
            secretKeyRef:
              name: mock-eq
              key: mock-eq
        - name: GOOGLE_CLOUD_PROJECT
          value: "{{ .Values.gcp.project }}"
        - name: PUBSUB_TOPIC
          value: "{{ .Values.gcp.topic }}"
        readinessProbe:
          httpGet:
            path: /info
            port: {{ .Values.container.port }}
          initialDelaySeconds: 1
          periodSeconds: 20
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: {{ .Values.container.port }}
          initialDelaySeconds: 1
          periodSeconds: 20
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
