apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-application-credentials
      containers:
      - name: {{ .Chart.Name }}
        {{- if eq .Values.image.tag "latest"}}
        image: "{{ .Values.image.name}}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        {{- else}}
        image: "{{ .Values.image.devRepo }}/{{ .Chart.Name }}:{{ .Values.image.tag }}"
        {{- end}}
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        ports:
        - name: http-server
          containerPort: {{ .Values.container.port }}
        resources:
          {{ toYaml .Values.resources | nindent 12 }}
        env:
        - name: JSON_SECRET_KEYS
          valueFrom:
            secretKeyRef:
              name: mock-eq
              key: mock-eq
        - name: GOOGLE_CLOUD_PROJECT
          value: "{{ .Values.gcp.project }}"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/credentials.json
        - name: PUBSUB_TOPIC
          value: "{{ .Values.gcp.topic }}"
        readinessProbe:
          httpGet:
            path: /info
            port: {{ .Values.container.port }}
          initialDelaySeconds: 1
          periodSeconds: 20
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: {{ .Values.container.port }}
          initialDelaySeconds: 1
          periodSeconds: 20
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 5
