apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mock-eq
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
    refreshInterval: 1m
  data:
  - secretKey: json-secret-keys-mock-eq
    remoteRef:
      key: mock-eq
      version: latest