apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  data:
  - secretKey: mock-eq
    remoteRef:
      key: json-secret-keys-mock-eq
      version: latest
