apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mock-eq
  namespace: arroya
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: json-secret-keys-mock-eq
      name: mock-eq
      version: latest
