apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.name }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: json-secret-keys-mock-eq
      name: mock-eq
      version: latest
