env: minikube
namespace: minikube

gcp:
  project: ras-rm-dev
  topic: sdx-receipt-dev

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

frontendConfig:
  sslPolicy: mock-eq-ingress-ssl-policy

ingress:
  enabled: false
  mockEqHost: mock-eq.example.com
  certNameMockEq: mock-eq-cert
  frontendConfigName: mock-eq-frontend-config
  timeoutSec: 30

resources:
  limits:
    cpu: "100m"
    memory: "150Mi"
  requests:
    cpu: "50m"
    memory: "100Mi"

container:
  port: 8080
service:
  type: "ClusterIP"
  port: 8080
