env: minikube
namespace: minikube

gcp:
  project: ras-rm-dev
  topic: sdx-receipt-dev

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always
