env: minikube
namespace: minikube

gcp:
  project: ras-rm-dev
  topic: sdx-receipt-dev

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "100m"
    memory: "150Mi"
  requests:
    cpu: "50m"
    memory: "100Mi"

container:
  port: 8080
service:
  type: "ClusterIP"
  port: 8080

dns:
  enabled: false
  wellKnownPort: 8080