name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: mock-eq
  CHART_DIRECTORY: _infra/helm/mock-eq

jobs:
  build:
    name: Check Helm and Chart versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683	 # v4.2.2

      - name: template helm
        if: github.actor != 'dependabot[bot]'
        run: |
          helm template $CHART_DIRECTORY

      - name: check version has been updated
        if: github.ref != 'refs/heads/main'
        shell: bash
        run: |
          echo "Current git version: ${{ env.tag }}"
          export APP_VERSION=$(grep -E "appVersion:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')
          export CHART_VERSION=$(grep -E "version:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')
          echo "appVersion: $APP_VERSION"
          echo "chartVersion: $CHART_VERSION"
          if [ ${{ env.tag }} = $APP_VERSION ]; then
            echo "App and chart version have not been updated"
            exit 1
          else
            if [ $APP_VERSION != $CHART_VERSION ]; then
              echo "app version manually updated without updating chart version"
              exit 1
            else
              echo "git version different to chart/app versions and chart/app versions match"
              echo "Using current version: $APP_VERSION"
            fi
          fi

      - name: output new version
        if: github.ref == 'refs/heads/main'
        id: release
        shell: bash
        run: |
          echo "version=$(grep -E "appVersion:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')" >> $GITHUB_ENV

