name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: mock-eq
  REGISTRY_HOSTNAME: europe-west2-docker.pkg.dev
  HOST: ${{ secrets.GOOGLE_PROJECT_ID }}
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
  RELEASE_HOST: ${{ secrets.RELEASE_PROJECT_ID }}
  CHART_DIRECTORY: _infra/helm/mock-eq
  SPINNAKER_TOPIC: ${{ secrets.SPINNAKER_TOPIC }}
  ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build & package"
  build:
    name: Check Helm and Chart versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683	 # v4.2.2
        with:
          fetch-depth: '0'
          token: ${{ secrets.BOT_TOKEN }}
      - name: pr docker tag
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        id: tag
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo "pr_number=pr-$PR" >> $GITHUB_ENV
          
      - name: template helm
        if: github.actor != 'dependabot[bot]'
        run: |
          helm template $CHART_DIRECTORY
      - name: Set current tag
        if: github.ref != 'refs/heads/main'
        id: vars
        run: |
          git fetch --tags
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: check version has been updated
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_GPG_KEY_PASSPHRASE: ${{ secrets.BOT_GPG_KEY_PASSPHRASE }}
          COMMIT_MSG: |
            auto patch increment
        shell: bash
        run: |
          echo "Current git version: ${{ env.tag }}"
          export APP_VERSION=$(grep -E "appVersion:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')
          export CHART_VERSION=$(grep -E "version:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')
          echo "appVersion: $APP_VERSION"
          echo "chartVersion: $CHART_VERSION"
          if [ ${{ env.tag }} = $APP_VERSION ]; then
            echo "App and chart version have not been updated"
            exit 1
          else
            if [ $APP_VERSION != $CHART_VERSION ]; then
              echo "app version manually updated without updating chart version"
              exit 1
            else
              echo "git version different to chart/app versions and chart/app versions match"
              echo "Using current version: $APP_VERSION"
            fi
          fi

      - name: output new version
        if: github.ref == 'refs/heads/main'
        id: release
        shell: bash
        run: |
          echo "version=$(grep -E "appVersion:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')" >> $GITHUB_ENV

